import type { Metadata } from "next";
import { Poppins, Montserrat } from 'next/font/google'
import "./globals.css";

const poppins = Poppins({
    subsets: ['latin'],
    weight: ['400', '500', '600', '700'],
    variable: '--font-poppins',
})

const montserrat = Montserrat({
    subsets: ['latin'],
    weight: ['400', '500', '600', '700'],
    variable: '--font-montserrat',
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fr" className={montserrat.variable}>
            <body className={`${montserrat.className} bg-background text-foreground`}>
                {children}
            </body>
        </html>
    );
}
